<?php
/**
 * Plugin Name: TSURILOGUE SEO Tools
 * Description: TSURILOGUE-MEDIA専用のSEO補助機能を管理します。
 * Version: 0.2.0
 * Author: TSURILOGUE
 * Text Domain: tsurilogue-seo-tools
 */

defined( 'ABSPATH' ) || exit;

const TSURILOGUE_SEO_TOOLS_VERSION    = '0.2.0';
const TSURILOGUE_SEO_TOOLS_ORIGIN_URL = 'https://tsurilogue.tapiyota.com';
const TSURILOGUE_SEO_TOOLS_PUBLIC_URL = 'https://www.tsurilogue.com/ja/media';
const TSURILOGUE_SEO_TOOLS_CTA_URL    = 'https://tsurilogue.com';

add_filter( 'ssp_output_canonical', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'ssp_output_og_url', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'get_canonical_url', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'post_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'page_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'post_type_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'term_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'the_permalink', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'home_url', 'tsurilogue_seo_tools_convert_frontend_home_url', 20, 4 );
add_filter( 'the_content', 'tsurilogue_seo_tools_append_article_cta', 20 );
add_action( 'wp_head', 'tsurilogue_seo_tools_maybe_output_structured_data', 20 );
add_action( 'wp_footer', 'tsurilogue_seo_tools_output_public_url_guard', 99 );
add_action( 'rest_api_init', 'tsurilogue_seo_tools_register_headless_routes' );

/**
 * Convert WordPress origin URLs to the public TSURILOGUE-MEDIA URL.
 *
 * @param string $url URL generated by WordPress, JIN, or SEO SIMPLE PACK.
 * @return string
 */
function tsurilogue_seo_tools_convert_public_url( $url ) {
	if ( ! is_string( $url ) || '' === $url ) {
		return $url;
	}

	$origin = untrailingslashit( TSURILOGUE_SEO_TOOLS_ORIGIN_URL );
	$public = untrailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL );

	if ( 0 === strpos( $url, $public ) ) {
		return tsurilogue_seo_tools_normalize_public_url( $url );
	}

	if ( 0 !== strpos( $url, $origin ) ) {
		return $url;
	}

	$path = substr( $url, strlen( $origin ) );
	$path = '/' . ltrim( (string) $path, '/' );

	return tsurilogue_seo_tools_normalize_public_url( trailingslashit( $public ) . ltrim( $path, '/' ) );
}

/**
 * Normalize accidental duplicate slashes immediately below the public media URL.
 *
 * @param string $url Public URL.
 * @return string
 */
function tsurilogue_seo_tools_normalize_public_url( $url ) {
	$public = trailingslashit( untrailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL ) );

	return str_replace( $public . '/', $public, $url );
}

/**
 * Convert frontend home URLs while leaving WordPress system paths untouched.
 *
 * @param string      $url         Full home URL.
 * @param string      $path        Path relative to the site root.
 * @param string|null $orig_scheme Requested scheme.
 * @param int|null    $blog_id     Blog ID.
 * @return string
 */
function tsurilogue_seo_tools_convert_frontend_home_url( $url, $path = '', $orig_scheme = null, $blog_id = null ) {
	unset( $orig_scheme, $blog_id );

	if ( is_admin() ) {
		return $url;
	}

	$path = '/' . ltrim( (string) $path, '/' );

	if ( preg_match( '#^/(wp-admin|wp-login\.php|wp-json|xmlrpc\.php|wp-content|wp-includes)(/|$)#', $path ) ) {
		return $url;
	}

	if ( '/' === $path ) {
		return untrailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL );
	}

	return tsurilogue_seo_tools_convert_public_url( $url );
}

/**
 * Add a frontend guard for links generated outside standard WordPress filters.
 *
 * @return void
 */
function tsurilogue_seo_tools_output_public_url_guard() {
	if ( is_admin() ) {
		return;
	}

	?>
	<script>
		(function () {
			var origin = <?php echo wp_json_encode( untrailingslashit( TSURILOGUE_SEO_TOOLS_ORIGIN_URL ) ); ?>;
			var publicUrl = <?php echo wp_json_encode( untrailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL ) ); ?>;

			function convertUrl(url) {
				if (!url || url.indexOf(origin) !== 0) {
					return url;
				}

				return publicUrl + "/" + url.slice(origin.length).replace(/^\/+/, "");
			}

			document.querySelectorAll("a[href]").forEach(function (anchor) {
				anchor.href = convertUrl(anchor.href);
			});

			document.querySelectorAll("form[action]").forEach(function (form) {
				form.action = convertUrl(form.action);
			});
		})();
	</script>
	<?php
}

/**
 * Register TSURILOGUE Headless Media REST endpoints.
 *
 * @return void
 */
function tsurilogue_seo_tools_register_headless_routes() {
	register_rest_route(
		'tsurilogue/v1',
		'/status',
		[
			'methods'             => 'GET',
			'callback'            => 'tsurilogue_seo_tools_rest_get_status',
			'permission_callback' => '__return_true',
		]
	);

	register_rest_route(
		'tsurilogue/v1',
		'/posts',
		[
			'methods'             => 'GET',
			'callback'            => 'tsurilogue_seo_tools_rest_get_posts',
			'permission_callback' => '__return_true',
			'args'                => [
				'page'     => [
					'default'           => 1,
					'sanitize_callback' => 'absint',
				],
				'per_page' => [
					'default'           => 10,
					'sanitize_callback' => 'absint',
				],
				'category' => [
					'sanitize_callback' => 'sanitize_title',
				],
				'tag'      => [
					'sanitize_callback' => 'sanitize_title',
				],
				'search'   => [
					'sanitize_callback' => 'sanitize_text_field',
				],
			],
		]
	);

	register_rest_route(
		'tsurilogue/v1',
		'/posts/(?P<slug>[a-zA-Z0-9_-]+)',
		[
			'methods'             => 'GET',
			'callback'            => 'tsurilogue_seo_tools_rest_get_post_by_slug',
			'permission_callback' => '__return_true',
		]
	);

	register_rest_route(
		'tsurilogue/v1',
		'/categories',
		[
			'methods'             => 'GET',
			'callback'            => 'tsurilogue_seo_tools_rest_get_categories',
			'permission_callback' => '__return_true',
		]
	);

	register_rest_route(
		'tsurilogue/v1',
		'/tags',
		[
			'methods'             => 'GET',
			'callback'            => 'tsurilogue_seo_tools_rest_get_tags',
			'permission_callback' => '__return_true',
		]
	);
}

/**
 * Return route/plugin status for deployment verification.
 *
 * @return WP_REST_Response
 */
function tsurilogue_seo_tools_rest_get_status() {
	return rest_ensure_response(
		[
			'ok'        => true,
			'plugin'    => 'TSURILOGUE SEO Tools',
			'version'   => TSURILOGUE_SEO_TOOLS_VERSION,
			'namespace' => 'tsurilogue/v1',
			'routes'    => [
				'/status',
				'/posts',
				'/posts/{slug}',
				'/categories',
				'/tags',
			],
		]
	);
}

/**
 * Return a paginated post collection for Next.js.
 *
 * @param WP_REST_Request $request REST request.
 * @return WP_REST_Response
 */
function tsurilogue_seo_tools_rest_get_posts( $request ) {
	$page     = max( 1, (int) $request->get_param( 'page' ) );
	$per_page = min( 20, max( 1, (int) $request->get_param( 'per_page' ) ) );
	$args     = [
		'post_type'           => 'post',
		'post_status'         => 'publish',
		'posts_per_page'      => $per_page,
		'paged'               => $page,
		'ignore_sticky_posts' => true,
	];

	$category = $request->get_param( 'category' );
	if ( $category ) {
		$args['category_name'] = $category;
	}

	$tag = $request->get_param( 'tag' );
	if ( $tag ) {
		$args['tag'] = $tag;
	}

	$search = $request->get_param( 'search' );
	if ( $search ) {
		$args['s'] = $search;
	}

	$query = new WP_Query( $args );
	$posts = array_map(
		function ( $post ) {
			return tsurilogue_seo_tools_prepare_headless_post( $post, true );
		},
		$query->posts
	);

	return rest_ensure_response(
		[
			'items'      => $posts,
			'pagination' => [
				'page'        => $page,
				'perPage'     => $per_page,
				'total'       => (int) $query->found_posts,
				'totalPages'  => (int) $query->max_num_pages,
				'hasNextPage' => $page < (int) $query->max_num_pages,
			],
		]
	);
}

/**
 * Return a single post by slug for Next.js.
 *
 * @param WP_REST_Request $request REST request.
 * @return WP_REST_Response|WP_Error
 */
function tsurilogue_seo_tools_rest_get_post_by_slug( $request ) {
	$slug  = sanitize_title( $request->get_param( 'slug' ) );
	$posts = get_posts(
		[
			'name'           => $slug,
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'posts_per_page' => 1,
		]
	);

	if ( empty( $posts ) ) {
		return new WP_Error( 'tsurilogue_post_not_found', 'Post not found.', [ 'status' => 404 ] );
	}

	return rest_ensure_response( tsurilogue_seo_tools_prepare_headless_post( $posts[0], true ) );
}

/**
 * Return categories for Next.js category pages.
 *
 * @return WP_REST_Response
 */
function tsurilogue_seo_tools_rest_get_categories() {
	return rest_ensure_response( tsurilogue_seo_tools_prepare_headless_terms( 'category' ) );
}

/**
 * Return tags for Next.js tag pages.
 *
 * @return WP_REST_Response
 */
function tsurilogue_seo_tools_rest_get_tags() {
	return rest_ensure_response( tsurilogue_seo_tools_prepare_headless_terms( 'post_tag' ) );
}

/**
 * Normalize a WordPress post for the Next.js media frontend.
 *
 * @param WP_Post $post Post object.
 * @param bool    $include_content Whether to include rendered content.
 * @return array
 */
function tsurilogue_seo_tools_prepare_headless_post( $post, $include_content = false ) {
	$post_id        = $post->ID;
	$featured_image = tsurilogue_seo_tools_get_headless_featured_image( $post_id );
	$excerpt        = get_the_excerpt( $post );
	$permalink      = tsurilogue_seo_tools_convert_public_url( get_permalink( $post_id ) );
	$data           = [
		'id'            => $post_id,
		'slug'          => $post->post_name,
		'url'           => $permalink,
		'title'         => [
			'raw'      => get_the_title( $post_id ),
			'rendered' => get_the_title( $post_id ),
		],
		'excerpt'       => [
			'raw'      => wp_strip_all_tags( $excerpt ),
			'rendered' => apply_filters( 'the_excerpt', $excerpt ),
		],
		'date'          => get_the_date( DATE_W3C, $post_id ),
		'modified'      => get_the_modified_date( DATE_W3C, $post_id ),
		'featuredImage' => $featured_image,
		'categories'    => tsurilogue_seo_tools_get_headless_post_terms( $post_id, 'category' ),
		'tags'          => tsurilogue_seo_tools_get_headless_post_terms( $post_id, 'post_tag' ),
		'seo'           => [
			'title'       => get_the_title( $post_id ),
			'description' => wp_trim_words( wp_strip_all_tags( $excerpt ), 80, '' ),
			'canonical'   => $permalink,
			'ogImage'     => $featured_image ? $featured_image['url'] : '',
		],
	];

	if ( $include_content ) {
		$data['content'] = [
			'raw'      => $post->post_content,
			'rendered' => apply_filters( 'the_content', $post->post_content ),
		];
	}

	return $data;
}

/**
 * Return normalized taxonomy terms.
 *
 * @param string $taxonomy Taxonomy name.
 * @return array
 */
function tsurilogue_seo_tools_prepare_headless_terms( $taxonomy ) {
	$terms = get_terms(
		[
			'taxonomy'   => $taxonomy,
			'hide_empty' => true,
		]
	);

	if ( is_wp_error( $terms ) ) {
		return [];
	}

	return array_map(
		function ( $term ) {
			return [
				'id'          => $term->term_id,
				'slug'        => $term->slug,
				'name'        => $term->name,
				'description' => $term->description,
				'count'       => (int) $term->count,
				'url'         => tsurilogue_seo_tools_convert_public_url( get_term_link( $term ) ),
			];
		},
		$terms
	);
}

/**
 * Return normalized terms attached to a post.
 *
 * @param int    $post_id Post ID.
 * @param string $taxonomy Taxonomy name.
 * @return array
 */
function tsurilogue_seo_tools_get_headless_post_terms( $post_id, $taxonomy ) {
	$terms = get_the_terms( $post_id, $taxonomy );

	if ( empty( $terms ) || is_wp_error( $terms ) ) {
		return [];
	}

	return array_map(
		function ( $term ) {
			return [
				'id'   => $term->term_id,
				'slug' => $term->slug,
				'name' => $term->name,
				'url'  => tsurilogue_seo_tools_convert_public_url( get_term_link( $term ) ),
			];
		},
		$terms
	);
}

/**
 * Return featured image information for Next.js image rendering.
 *
 * @param int $post_id Post ID.
 * @return array|null
 */
function tsurilogue_seo_tools_get_headless_featured_image( $post_id ) {
	$image_id = get_post_thumbnail_id( $post_id );

	if ( ! $image_id ) {
		return null;
	}

	$src = wp_get_attachment_image_src( $image_id, 'full' );

	if ( ! $src ) {
		return null;
	}

	return [
		'id'     => $image_id,
		'url'    => $src[0],
		'width'  => (int) $src[1],
		'height' => (int) $src[2],
		'alt'    => get_post_meta( $image_id, '_wp_attachment_image_alt', true ),
	];
}

/**
 * Determine whether article CTA output is enabled.
 *
 * @return bool
 */
function tsurilogue_seo_tools_is_article_cta_enabled() {
	return (bool) apply_filters( 'tsurilogue_seo_tools_enable_article_cta', true );
}

/**
 * Append the TSURILOGUE CTA to single post content.
 *
 * @param string $content Post content.
 * @return string
 */
function tsurilogue_seo_tools_append_article_cta( $content ) {
	if ( is_admin() || ! tsurilogue_seo_tools_is_article_cta_enabled() ) {
		return $content;
	}

	if ( ! is_singular( 'post' ) || ! in_the_loop() || ! is_main_query() ) {
		return $content;
	}

	return $content . tsurilogue_seo_tools_get_article_cta_html();
}

/**
 * Build article CTA markup.
 *
 * @return string
 */
function tsurilogue_seo_tools_get_article_cta_html() {
	$title = '今日の釣果、未来につながります。';
	$body  = 'TSURILOGUEなら、潮位・風向・水温・釣果写真・タックル情報をまとめて記録できます。記録を重ねるほど、自分だけの釣れる条件が見えてきます。';
	$label = '無料でTSURILOGUEをはじめる';

	ob_start();
	?>
	<section class="tsurilogue-cta tsurilogue-article-cta" aria-labelledby="tsurilogue-article-cta-title">
		<div class="tsurilogue-cta__body">
			<h2 class="tsurilogue-cta__title" id="tsurilogue-article-cta-title"><?php echo esc_html( $title ); ?></h2>
			<p class="tsurilogue-cta__text"><?php echo esc_html( $body ); ?></p>
			<a class="tsurilogue-button tsurilogue-cta__button" href="<?php echo esc_url( TSURILOGUE_SEO_TOOLS_CTA_URL ); ?>">
				<?php echo esc_html( $label ); ?>
			</a>
		</div>
	</section>
	<?php
	return (string) ob_get_clean();
}

/**
 * Determine whether supplemental structured data output is enabled.
 *
 * Disabled by default to avoid duplicate output with JIN or SEO SIMPLE PACK.
 *
 * @return bool
 */
function tsurilogue_seo_tools_is_structured_data_enabled() {
	return (bool) apply_filters( 'tsurilogue_seo_tools_enable_structured_data', false );
}

/**
 * Output supplemental JSON-LD only when explicitly enabled.
 *
 * @return void
 */
function tsurilogue_seo_tools_maybe_output_structured_data() {
	if ( is_admin() || ! tsurilogue_seo_tools_is_structured_data_enabled() ) {
		return;
	}

	$data = tsurilogue_seo_tools_get_structured_data();

	if ( empty( $data ) ) {
		return;
	}

	echo "\n" . '<script type="application/ld+json">' . wp_json_encode( $data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) . '</script>' . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}

/**
 * Build a minimal structured data graph.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_structured_data() {
	$graph = [
		tsurilogue_seo_tools_get_organization_schema(),
	];

	if ( is_singular( 'post' ) ) {
		$graph[] = tsurilogue_seo_tools_get_article_schema();
	}

	$breadcrumb = tsurilogue_seo_tools_get_breadcrumb_schema();
	if ( ! empty( $breadcrumb ) ) {
		$graph[] = $breadcrumb;
	}

	return [
		'@context' => 'https://schema.org',
		'@graph'   => array_values( array_filter( $graph ) ),
	];
}

/**
 * Build Organization schema.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_organization_schema() {
	return [
		'@type' => 'Organization',
		'@id'   => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ) . '#organization',
		'name'  => 'TSURILOGUE',
		'url'   => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ),
	];
}

/**
 * Build Article schema for posts.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_article_schema() {
	$post_id = get_queried_object_id();

	if ( ! $post_id ) {
		return [];
	}

	$permalink = tsurilogue_seo_tools_convert_public_url( get_permalink( $post_id ) );
	$image_id  = get_post_thumbnail_id( $post_id );
	$image     = $image_id ? wp_get_attachment_image_url( $image_id, 'full' ) : '';

	$schema = [
		'@type'         => 'Article',
		'@id'           => trailingslashit( $permalink ) . '#article',
		'headline'      => get_the_title( $post_id ),
		'mainEntityOfPage' => $permalink,
		'datePublished' => get_the_date( DATE_W3C, $post_id ),
		'dateModified'  => get_the_modified_date( DATE_W3C, $post_id ),
		'publisher'     => [
			'@id' => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ) . '#organization',
		],
	];

	if ( $image ) {
		$schema['image'] = $image;
	}

	return $schema;
}

/**
 * Build a minimal BreadcrumbList schema.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_breadcrumb_schema() {
	if ( ! is_singular( 'post' ) ) {
		return [];
	}

	$post_id = get_queried_object_id();
	$items   = [
		[
			'@type'    => 'ListItem',
			'position' => 1,
			'name'     => 'TSURILOGUE-MEDIA',
			'item'     => trailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL ),
		],
	];

	$categories = get_the_category( $post_id );
	if ( ! empty( $categories ) ) {
		$category = $categories[0];
		$items[]  = [
			'@type'    => 'ListItem',
			'position' => count( $items ) + 1,
			'name'     => $category->name,
			'item'     => tsurilogue_seo_tools_convert_public_url( get_category_link( $category ) ),
		];
	}

	$items[] = [
		'@type'    => 'ListItem',
		'position' => count( $items ) + 1,
		'name'     => get_the_title( $post_id ),
		'item'     => tsurilogue_seo_tools_convert_public_url( get_permalink( $post_id ) ),
	];

	return [
		'@type'           => 'BreadcrumbList',
		'itemListElement' => $items,
	];
}
