<?php
/**
 * Plugin Name: TSURILOGUE SEO Tools
 * Description: TSURILOGUE-MEDIA専用のSEO補助機能を管理します。
 * Version: 0.1.0
 * Author: TSURILOGUE
 * Text Domain: tsurilogue-seo-tools
 */

defined( 'ABSPATH' ) || exit;

const TSURILOGUE_SEO_TOOLS_VERSION    = '0.1.0';
const TSURILOGUE_SEO_TOOLS_ORIGIN_URL = 'https://tsurilogue.tapiyota.com';
const TSURILOGUE_SEO_TOOLS_PUBLIC_URL = 'https://www.tsurilogue.com/ja/media';
const TSURILOGUE_SEO_TOOLS_CTA_URL    = 'https://tsurilogue.com';

add_filter( 'ssp_output_canonical', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'ssp_output_og_url', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'get_canonical_url', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'post_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'page_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'post_type_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'term_link', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'the_permalink', 'tsurilogue_seo_tools_convert_public_url', 20 );
add_filter( 'home_url', 'tsurilogue_seo_tools_convert_frontend_home_url', 20, 4 );
add_filter( 'the_content', 'tsurilogue_seo_tools_append_article_cta', 20 );
add_action( 'wp_head', 'tsurilogue_seo_tools_maybe_output_structured_data', 20 );

/**
 * Convert WordPress origin URLs to the public TSURILOGUE-MEDIA URL.
 *
 * @param string $url URL generated by WordPress, JIN, or SEO SIMPLE PACK.
 * @return string
 */
function tsurilogue_seo_tools_convert_public_url( $url ) {
	if ( ! is_string( $url ) || '' === $url ) {
		return $url;
	}

	$origin = untrailingslashit( TSURILOGUE_SEO_TOOLS_ORIGIN_URL );
	$public = untrailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL );

	if ( 0 !== strpos( $url, $origin ) ) {
		return $url;
	}

	$path = substr( $url, strlen( $origin ) );
	$path = '/' . ltrim( (string) $path, '/' );

	return trailingslashit( $public ) . ltrim( $path, '/' );
}

/**
 * Convert frontend home URLs while leaving WordPress system paths untouched.
 *
 * @param string      $url         Full home URL.
 * @param string      $path        Path relative to the site root.
 * @param string|null $orig_scheme Requested scheme.
 * @param int|null    $blog_id     Blog ID.
 * @return string
 */
function tsurilogue_seo_tools_convert_frontend_home_url( $url, $path = '', $orig_scheme = null, $blog_id = null ) {
	unset( $orig_scheme, $blog_id );

	if ( is_admin() ) {
		return $url;
	}

	$path = '/' . ltrim( (string) $path, '/' );

	if ( preg_match( '#^/(wp-admin|wp-login\.php|wp-json|xmlrpc\.php|wp-content|wp-includes)(/|$)#', $path ) ) {
		return $url;
	}

	return tsurilogue_seo_tools_convert_public_url( $url );
}

/**
 * Determine whether article CTA output is enabled.
 *
 * @return bool
 */
function tsurilogue_seo_tools_is_article_cta_enabled() {
	return (bool) apply_filters( 'tsurilogue_seo_tools_enable_article_cta', true );
}

/**
 * Append the TSURILOGUE CTA to single post content.
 *
 * @param string $content Post content.
 * @return string
 */
function tsurilogue_seo_tools_append_article_cta( $content ) {
	if ( is_admin() || ! tsurilogue_seo_tools_is_article_cta_enabled() ) {
		return $content;
	}

	if ( ! is_singular( 'post' ) || ! in_the_loop() || ! is_main_query() ) {
		return $content;
	}

	return $content . tsurilogue_seo_tools_get_article_cta_html();
}

/**
 * Build article CTA markup.
 *
 * @return string
 */
function tsurilogue_seo_tools_get_article_cta_html() {
	$title = '今日の釣果、未来につながります。';
	$body  = 'TSURILOGUEなら、潮位・風向・水温・釣果写真・タックル情報をまとめて記録できます。記録を重ねるほど、自分だけの釣れる条件が見えてきます。';
	$label = '無料でTSURILOGUEをはじめる';

	ob_start();
	?>
	<section class="tsurilogue-cta tsurilogue-article-cta" aria-labelledby="tsurilogue-article-cta-title">
		<div class="tsurilogue-cta__body">
			<h2 class="tsurilogue-cta__title" id="tsurilogue-article-cta-title"><?php echo esc_html( $title ); ?></h2>
			<p class="tsurilogue-cta__text"><?php echo esc_html( $body ); ?></p>
			<a class="tsurilogue-button tsurilogue-cta__button" href="<?php echo esc_url( TSURILOGUE_SEO_TOOLS_CTA_URL ); ?>">
				<?php echo esc_html( $label ); ?>
			</a>
		</div>
	</section>
	<?php
	return (string) ob_get_clean();
}

/**
 * Determine whether supplemental structured data output is enabled.
 *
 * Disabled by default to avoid duplicate output with JIN or SEO SIMPLE PACK.
 *
 * @return bool
 */
function tsurilogue_seo_tools_is_structured_data_enabled() {
	return (bool) apply_filters( 'tsurilogue_seo_tools_enable_structured_data', false );
}

/**
 * Output supplemental JSON-LD only when explicitly enabled.
 *
 * @return void
 */
function tsurilogue_seo_tools_maybe_output_structured_data() {
	if ( is_admin() || ! tsurilogue_seo_tools_is_structured_data_enabled() ) {
		return;
	}

	$data = tsurilogue_seo_tools_get_structured_data();

	if ( empty( $data ) ) {
		return;
	}

	echo "\n" . '<script type="application/ld+json">' . wp_json_encode( $data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) . '</script>' . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}

/**
 * Build a minimal structured data graph.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_structured_data() {
	$graph = [
		tsurilogue_seo_tools_get_organization_schema(),
	];

	if ( is_singular( 'post' ) ) {
		$graph[] = tsurilogue_seo_tools_get_article_schema();
	}

	$breadcrumb = tsurilogue_seo_tools_get_breadcrumb_schema();
	if ( ! empty( $breadcrumb ) ) {
		$graph[] = $breadcrumb;
	}

	return [
		'@context' => 'https://schema.org',
		'@graph'   => array_values( array_filter( $graph ) ),
	];
}

/**
 * Build Organization schema.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_organization_schema() {
	return [
		'@type' => 'Organization',
		'@id'   => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ) . '#organization',
		'name'  => 'TSURILOGUE',
		'url'   => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ),
	];
}

/**
 * Build Article schema for posts.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_article_schema() {
	$post_id = get_queried_object_id();

	if ( ! $post_id ) {
		return [];
	}

	$permalink = tsurilogue_seo_tools_convert_public_url( get_permalink( $post_id ) );
	$image_id  = get_post_thumbnail_id( $post_id );
	$image     = $image_id ? wp_get_attachment_image_url( $image_id, 'full' ) : '';

	$schema = [
		'@type'         => 'Article',
		'@id'           => trailingslashit( $permalink ) . '#article',
		'headline'      => get_the_title( $post_id ),
		'mainEntityOfPage' => $permalink,
		'datePublished' => get_the_date( DATE_W3C, $post_id ),
		'dateModified'  => get_the_modified_date( DATE_W3C, $post_id ),
		'publisher'     => [
			'@id' => trailingslashit( TSURILOGUE_SEO_TOOLS_CTA_URL ) . '#organization',
		],
	];

	if ( $image ) {
		$schema['image'] = $image;
	}

	return $schema;
}

/**
 * Build a minimal BreadcrumbList schema.
 *
 * @return array
 */
function tsurilogue_seo_tools_get_breadcrumb_schema() {
	if ( ! is_singular( 'post' ) ) {
		return [];
	}

	$post_id = get_queried_object_id();
	$items   = [
		[
			'@type'    => 'ListItem',
			'position' => 1,
			'name'     => 'TSURILOGUE-MEDIA',
			'item'     => trailingslashit( TSURILOGUE_SEO_TOOLS_PUBLIC_URL ),
		],
	];

	$categories = get_the_category( $post_id );
	if ( ! empty( $categories ) ) {
		$category = $categories[0];
		$items[]  = [
			'@type'    => 'ListItem',
			'position' => count( $items ) + 1,
			'name'     => $category->name,
			'item'     => tsurilogue_seo_tools_convert_public_url( get_category_link( $category ) ),
		];
	}

	$items[] = [
		'@type'    => 'ListItem',
		'position' => count( $items ) + 1,
		'name'     => get_the_title( $post_id ),
		'item'     => tsurilogue_seo_tools_convert_public_url( get_permalink( $post_id ) ),
	];

	return [
		'@type'           => 'BreadcrumbList',
		'itemListElement' => $items,
	];
}
